# docker-compose.yml
version: '3.7'
services:
  jenkins:
    build:
      context: .
    privileged: true
    user: root
    ports:
      - 8060:8080
      - 50003:50000
    container_name: my-jenkins-3
    volumes:
      - ./jenkins_info:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock